"""fixing foreign key of biometrics

Revision ID: 002f95fb7b55
Revises: b711d3af626a
Create Date: 2022-01-31 18:40:41.513323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002f95fb7b55'
down_revision = 'b711d3af626a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients_biometrics', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('clients_biometrics_client_id_key', 'clients_biometrics', type_='unique')
    op.create_unique_constraint(None, 'clients_biometrics', ['user_id'])
    op.drop_constraint('clients_biometrics_client_id_fkey', 'clients_biometrics', type_='foreignkey')
    op.create_foreign_key(None, 'clients_biometrics', 'clients', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('clients_biometrics', 'client_id')
    op.drop_column('clients_biometrics', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients_biometrics', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.add_column('clients_biometrics', sa.Column('client_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'clients_biometrics', type_='foreignkey')
    op.create_foreign_key('clients_biometrics_client_id_fkey', 'clients_biometrics', 'clients', ['client_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'clients_biometrics', type_='unique')
    op.create_unique_constraint('clients_biometrics_client_id_key', 'clients_biometrics', ['client_id'])
    op.drop_column('clients_biometrics', 'user_id')
    # ### end Alembic commands ###
