"""added credentials and addresses tables

Revision ID: 05838fdafe6c
Revises: a6681410bb5b
Create Date: 2022-01-29 19:37:38.995777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05838fdafe6c'
down_revision = 'a6681410bb5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('password_salt', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_email'), 'credentials', ['email'], unique=True)
    op.create_table('addresses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('address_name', sa.Text(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.Column('street', sa.Text(), nullable=False),
    sa.Column('building', sa.Text(), nullable=False),
    sa.Column('floor', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('first_name', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('phone_number', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('user_type', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('credentials_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'users', 'credentials', ['credentials_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'credentials_id')
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_credentials_email'), table_name='credentials')
    op.drop_table('credentials')
    # ### end Alembic commands ###
