"""image for meal plan

Revision ID: 0616b5d9a52d
Revises: 44ae0eeb8291
Create Date: 2022-03-27 22:13:50.799315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0616b5d9a52d'
down_revision = '44ae0eeb8291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_providers_meal_plans', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_providers_meal_plans', 'image')
    # ### end Alembic commands ###
