"""added categories table

Revision ID: 0c0066633a9f
Revises: d6b8fcbfe229
Create Date: 2022-02-20 17:37:41.589399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0066633a9f'
down_revision = 'd6b8fcbfe229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('truncate "Item" cascade')
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['service_providers.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category'),
    sa.UniqueConstraint('category'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('Item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Item',
    sa.Column('id', sa.BIGINT(), server_default=sa.text('nextval(\'"Item_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['service_providers.user_id'], name='Item_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Item_pkey'),
    sa.UniqueConstraint('category', name='Item_category_key'),
    sa.UniqueConstraint('description', name='Item_description_key'),
    sa.UniqueConstraint('name', name='Item_name_key')
    )
    op.drop_table('items')
    op.drop_table('categories')
    # ### end Alembic commands ###
