"""Added service provider meal plan table

Revision ID: 2d8946a8833a
Revises: 4a514124fe11
Create Date: 2022-01-30 19:12:49.229099

"""
from alembic import op
import sqlalchemy as sa

from database.models.clients_biometrics import ClientBiometrics


# revision identifiers, used by Alembic.
revision = '2d8946a8833a'
down_revision = '4a514124fe11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clients_biometrics_client_id_fkey', 'clients_biometrics', type_='foreignkey')
    op.create_foreign_key(None, 'clients_biometrics', 'clients', ['client_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('service_providers_user_id_key', 'service_providers', type_='unique')
    op.drop_column('clients', 'id')
    op.drop_column('service_providers', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_providers', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.create_unique_constraint('service_providers_user_id_key', 'service_providers', ['user_id'])
    op.drop_constraint(None, 'clients_biometrics', type_='foreignkey')
    op.create_foreign_key('clients_biometrics_client_id_fkey', 'clients_biometrics', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.add_column('clients', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
