"""adding password to users

Revision ID: 340e96fab76d
Revises: 35b81645356e
Create Date: 2022-01-02 17:42:28.292017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340e96fab76d'
down_revision = '35b81645356e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
