"""added server default

Revision ID: 4808e44c6017
Revises: 5e3ee449d4fe
Create Date: 2022-04-24 00:59:02.373670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4808e44c6017'
down_revision = '5e3ee449d4fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('image_url', sa.Text(), server_default=sa.text("'https://299storage.blob.core.windows.net/container/meals_default.svg'"), nullable=True))
    op.add_column('service_providers', sa.Column('img_url', sa.Text(), server_default=sa.text("'https://299storage.blob.core.windows.net/container/blank-profile-picture.png'"), nullable=True))
    op.add_column('service_providers_meal_plans', sa.Column('image', sa.Text(), server_default=sa.text("'https://299storage.blob.core.windows.net/container/meal-plan-default.jpeg'"), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_providers_meal_plans', 'image')
    op.drop_column('service_providers', 'img_url')
    op.drop_column('items', 'image_url')
    # ### end Alembic commands ###
