"""added column id to users

Revision ID: 49d899dd8809
Revises: b7559dad8106
Create Date: 2022-01-02 18:31:31.305380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d899dd8809'
down_revision = 'b7559dad8106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, primary_key=True))
    op.alter_column('users', 'first_name',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'first_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('users', 'id')
    # ### end Alembic commands ###
