"""ergew

Revision ID: 5e3ee449d4fe
Revises: c00ae07119c7
Create Date: 2022-04-24 00:58:32.302921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e3ee449d4fe'
down_revision = 'c00ae07119c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'image_url')
    op.drop_column('service_providers', 'img_url')
    op.drop_column('service_providers_meal_plans', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_providers_meal_plans', sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('service_providers', sa.Column('img_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
