"""empty message

Revision ID: 67d9e54cab8c
Revises: 9a6397776743
Create Date: 2022-04-07 03:19:20.805322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d9e54cab8c'
down_revision = '9a6397776743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
