"""added availability columns

Revision ID: 722d4f7d05b6
Revises: af88586d6111
Create Date: 2022-05-04 14:33:11.736599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722d4f7d05b6'
down_revision = 'af88586d6111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('isavailable', sa.Boolean(), nullable=False))
    op.add_column('service_providers_meal_plans', sa.Column('isavailable', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_providers_meal_plans', 'isavailable')
    op.drop_column('items', 'isavailable')
    # ### end Alembic commands ###
