"""empty message

Revision ID: 9a6397776743
Revises: bbe9cde5b88e
Create Date: 2022-04-07 03:12:59.801839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a6397776743'
down_revision = 'bbe9cde5b88e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
