"""added address to service providers

Revision ID: a06b7bbfa864
Revises: 03473261dea8
Create Date: 2022-05-01 15:11:07.826650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a06b7bbfa864'
down_revision = '03473261dea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_providers', sa.Column('address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_providers', 'address')
    # ### end Alembic commands ###
