"""YOUR DESCRIPTION HERE

Revision ID: a6681410bb5b
Revises: 171ca57eff91
Create Date: 2022-01-20 15:57:24.468320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6681410bb5b'
down_revision = '171ca57eff91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
