"""added last ordered meal date

Revision ID: af88586d6111
Revises: a06b7bbfa864
Create Date: 2022-05-01 16:52:02.382721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af88586d6111'
down_revision = 'a06b7bbfa864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('last_ordered_meal_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'last_ordered_meal_date')
    # ### end Alembic commands ###
