"""Added meal plan price table

Revision ID: b711d3af626a
Revises: 75e21f65b537
Create Date: 2022-01-30 20:03:45.333729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b711d3af626a'
down_revision = '75e21f65b537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_plans_prices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('price', sa.REAL(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('meal_plan_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['service_provdiders_meal_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_plans_prices')
    # ### end Alembic commands ###
