"""added users model

Revision ID: b7559dad8106
Revises: c1332cd29de1
Create Date: 2022-01-02 18:24:52.721990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7559dad8106'
down_revision = 'c1332cd29de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('first_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
