"""empty message

Revision ID: bbe9cde5b88e
Revises: 2c90a193c5de
Create Date: 2022-04-07 03:09:51.747566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe9cde5b88e'
down_revision = '2c90a193c5de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('meal_plan_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('clients__meal_plan_id_fkey', 'clients', type_='foreignkey')
    op.create_foreign_key(None, 'clients', 'service_providers_meal_plans', ['meal_plan_id'], ['id'], ondelete='CASCADE')
    op.drop_column('clients', '_meal_plan_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('_meal_plan_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.create_foreign_key('clients__meal_plan_id_fkey', 'clients', 'service_providers_meal_plans', ['_meal_plan_id'], ['id'], ondelete='CASCADE')
    op.drop_column('clients', 'meal_plan_id')
    # ### end Alembic commands ###
