"""added server default

Revision ID: c00ae07119c7
Revises: 0ef217b81b1a
Create Date: 2022-04-24 00:57:21.554625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00ae07119c7'
down_revision = '0ef217b81b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
