"""empty message

Revision ID: c08b0401975a
Revises: f46167626d74
Create Date: 2022-04-07 02:35:28.810332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08b0401975a'
down_revision = 'f46167626d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'meal_plan_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'meal_plan_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
