"""unique service provider name

Revision ID: cda8db07a7de
Revises: 648a9dc4e6ae
Create Date: 2022-02-01 15:35:45.747385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda8db07a7de'
down_revision = '648a9dc4e6ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'service_providers', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_providers', type_='unique')
    # ### end Alembic commands ###
