"""added city to addresses

Revision ID: d9ad11835896
Revises: 44ae0eeb8291
Create Date: 2022-03-30 14:11:02.895878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ad11835896'
down_revision = '44ae0eeb8291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('city', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'city')
    # ### end Alembic commands ###
