"""added meal plan uses

Revision ID: e0c88f77d63d
Revises: ee4c0cc7e442
Create Date: 2022-04-17 23:06:55.720546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0c88f77d63d'
down_revision = 'ee4c0cc7e442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_providers_meal_plans', sa.Column('meal_plan_uses', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_providers_meal_plans', 'meal_plan_uses')
    # ### end Alembic commands ###
