"""empty message

Revision ID: e90cdf7aa52d
Revises: efe4e9b0d648
Create Date: 2022-04-05 17:59:20.467523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90cdf7aa52d'
down_revision = 'efe4e9b0d648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('meal_plans', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'clients', 'service_providers_meal_plans', ['meal_plans'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'meal_plans')
    # ### end Alembic commands ###
