"""added sub counter

Revision ID: ee4c0cc7e442
Revises: 67d9e54cab8c
Create Date: 2022-04-17 18:01:59.224894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee4c0cc7e442'
down_revision = '67d9e54cab8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('subscription_counter', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'subscription_counter')
    # ### end Alembic commands ###
