"""empty message

Revision ID: f46167626d74
Revises: e90cdf7aa52d
Create Date: 2022-04-07 01:58:00.908771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46167626d74'
down_revision = 'e90cdf7aa52d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('meal_plan_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('clients_meal_plans_fkey', 'clients', type_='foreignkey')
    op.create_foreign_key(None, 'clients', 'service_providers_meal_plans', ['meal_plan_id'], ['id'], ondelete='CASCADE')
    op.drop_column('clients', 'meal_plans')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('meal_plans', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.create_foreign_key('clients_meal_plans_fkey', 'clients', 'service_providers_meal_plans', ['meal_plans'], ['id'], ondelete='CASCADE')
    op.drop_column('clients', 'meal_plan_id')
    # ### end Alembic commands ###
